/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {

        "primary-fixed-dim": "var(--primary-fixed-dim)",
        "surface-container-low": "var(--surface-container-low)",
        "primary-fixed": "var(--primary-fixed)",
        "on-error": "var(--on-error)",
        "surface-variant": "var(--surface-variant)",
        "inverse-primary": "var(--inverse-primary)",
        "tertiary-container": "var(--tertiary-container)",
        "surface-container-lowest": "var(--surface-container-lowest)",
        "tertiary": "var(--tertiary)",
        "error-container": "var(--error-container)",
        "inverse-surface": "var(--inverse-surface)",
        "outline": "var(--outline)",
        "on-primary-container": "var(--on-primary-container)",
        "on-primary-fixed-variant": "var(--on-primary-fixed-variant)",
        "inverse-on-surface": "var(--inverse-on-surface)",
        "secondary-fixed": "var(--secondary-fixed)",
        "on-background": "var(--on-background)",
        "surface-bright": "var(--surface-bright)",
        "primary-container": "var(--primary-container)",
        "on-surface": "var(--on-surface)",
        "on-tertiary": "var(--on-tertiary)",
        "surface": "var(--surface)",
        "on-surface-variant": "var(--on-surface-variant)",
        "background": "var(--background)",
        "on-primary-fixed": "var(--on-primary-fixed)",
        "on-secondary-fixed": "var(--on-secondary-fixed)",
        "error": "var(--error)",
        "on-secondary-fixed-variant": "var(--on-secondary-fixed-variant)",
        "tertiary-fixed-dim": "var(--tertiary-fixed-dim)",
        "on-error-container": "var(--on-error-container)",
        "primary": "var(--primary)",
        "secondary-container": "var(--secondary-container)",
        "on-tertiary-fixed": "var(--on-tertiary-fixed)",
        "outline-variant": "var(--outline-variant)",
        "surface-tint": "var(--surface-tint)",
        "surface-container-highest": "var(--surface-container-highest)",
        "on-tertiary-fixed-variant": "var(--on-tertiary-fixed-variant)",
        "on-primary": "var(--on-primary)",
        "on-secondary-container": "var(--on-secondary-container)",
        "tertiary-fixed": "var(--tertiary-fixed)",
        "secondary-fixed-dim": "var(--secondary-fixed-dim)",
        "surface-container": "var(--surface-container)",
        "secondary": "var(--secondary)",
        "on-tertiary-container": "var(--on-tertiary-container)",
        "surface-dim": "var(--surface-dim)",
        "surface-container-high": "var(--surface-container-high)",
        "on-secondary": "var(--on-secondary)",
      
},
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "24px",
        "xl": "32px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xs": "4px",
        "xxl": "48px",
        "base": "4px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
