/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b4c5ff",
        "surface-container-low": "#f2f3ff",
        "primary-fixed": "#dbe1ff",
        "on-error": "#ffffff",
        "surface-variant": "#dae2fd",
        "inverse-primary": "#b4c5ff",
        "tertiary-container": "#996100",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#784b00",
        "error-container": "#ffdad6",
        "inverse-surface": "#283044",
        "outline": "#737686",
        "on-primary-container": "#eeefff",
        "on-primary-fixed-variant": "#003ea8",
        "inverse-on-surface": "#eef0ff",
        "secondary-fixed": "#6ffbbe",
        "on-background": "#131b2e",
        "surface-bright": "#faf8ff",
        "primary-container": "#2563eb",
        "on-surface": "#131b2e",
        "on-tertiary": "#ffffff",
        "surface": "#faf8ff",
        "on-surface-variant": "#434655",
        "background": "#faf8ff",
        "on-primary-fixed": "#00174b",
        "on-secondary-fixed": "#002113",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed-dim": "#ffb95f",
        "on-error-container": "#93000a",
        "primary": "#004ac6",
        "secondary-container": "#6cf8bb",
        "on-tertiary-fixed": "#2a1700",
        "outline-variant": "#c3c6d7",
        "surface-tint": "#0053db",
        "surface-container-highest": "#dae2fd",
        "on-tertiary-fixed-variant": "#653e00",
        "on-primary": "#ffffff",
        "on-secondary-container": "#00714d",
        "tertiary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#4edea3",
        "surface-container": "#eaedff",
        "secondary": "#006c49",
        "on-tertiary-container": "#ffeedd",
        "surface-dim": "#d2d9f4",
        "surface-container-high": "#e2e7ff",
        "on-secondary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-margin": "24px",
        "xl": "32px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xs": "4px",
        "xxl": "48px",
        "base": "4px",
        "gutter": "16px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "display": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    }
  },
  plugins: [],
}
