-- ============================================================
-- AulaIA — Migración V2: tabla usuarios (docs/04-BASE_DE_DATOS §6.1)
-- ============================================================
-- Cuentas de acceso para administradores y docentes.
-- Los estudiantes NO tienen cuenta (asistencia en Modo Aula).
-- password_hash nunca almacena contraseña plana (se poblará con
-- BCrypt en prompts posteriores del Sprint 2).
-- ============================================================

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    rol VARCHAR(30) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    ultimo_login_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_usuarios_rol CHECK (rol IN ('ADMIN', 'DOCENTE'))
);