-- ============================================================
-- AulaIA — Migración V3: tabla grados (docs/04-BASE_DE_DATOS §6.3)
-- ============================================================
-- Catálogo de grados escolares (p. ej. 5.º Primaria, 6.º Primaria).
--
-- Modelo oficial (04-BD §6.3): id, nombre, nivel (default 'PRIMARIA'),
-- orden (nullable), activo (default TRUE), created_at. NO tiene columna
-- updated_at y NO define unicidad sobre nombre; se respeta tal cual.
--
-- Solo estructura: los datos demo se crean en un seed de desarrollo
-- separado (Prompt 23.1), nunca en migraciones.
-- ============================================================

CREATE TABLE grados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(80) NOT NULL,
    nivel VARCHAR(50) NOT NULL DEFAULT 'PRIMARIA',
    orden SMALLINT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_grados_orden CHECK (orden IS NULL OR orden >= 0)
);