-- ============================================================
-- AulaIA — Migración V4: tabla secciones (docs/04-BASE_DE_DATOS §6.4)
-- ============================================================
-- Sección académica dentro de un grado y periodo
-- (p. ej. Grado 6.º Primaria, Sección A, Periodo 2026).
--
-- Modelo oficial (04-BD §6.4): id, grado_id (FK a grados), nombre,
-- periodo_academico, activo (default TRUE), created_at, updated_at.
-- A diferencia de grados, el modelo oficial SÍ define updated_at aquí.
--
-- Restricción única oficial: uq_seccion_grado_periodo
-- UNIQUE (grado_id, nombre, periodo_academico): dentro del mismo grado y
-- mismo periodo académico no pueden existir dos secciones con el mismo
-- nombre. El mismo nombre sí puede repetirse en otro grado u otro periodo.
--
-- La FK fk_secciones_grado impide referencias a grados inexistentes.
-- Sin ON DELETE CASCADE: los documentos no lo exigen.
--
-- Solo estructura: los datos demo se crean en un seed de desarrollo
-- separado (Prompt 23.1), nunca en migraciones.
-- ============================================================

CREATE TABLE secciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grado_id BIGINT NOT NULL,
    nombre VARCHAR(20) NOT NULL,
    periodo_academico VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_secciones_grado
        FOREIGN KEY (grado_id)
        REFERENCES grados(id),

    CONSTRAINT uq_seccion_grado_periodo
        UNIQUE (grado_id, nombre, periodo_academico)
);
