-- ============================================================
-- AulaIA — Migración V5: tabla cursos (docs/04-BASE_DE_DATOS §6.6)
-- ============================================================
-- Catálogo de cursos (p. ej. "Computación").
--
-- Modelo oficial (04-BD §6.6): id, nombre, descripcion, activo
-- (default TRUE), created_at, updated_at.
--
-- Sin UNIQUE ni CHECK: 04-BD §6.6 no define ninguna restricción de
-- unicidad sobre nombre ni validaciones adicionales. La BD permite
-- dos cursos con el mismo nombre.
--
-- Sin FKs: el modelo oficial no define relaciones en esta tabla
-- (las referencias a cursos llegan desde horarios, módulo futuro).
--
-- Solo estructura: los datos demo se crean en un seed de desarrollo
-- separado (Prompt 23.1), nunca en migraciones.
-- ============================================================

CREATE TABLE cursos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255) NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);