-- ============================================================
-- AulaIA — Migración V6: tabla estudiantes (docs/04-BASE_DE_DATOS §6.5)
-- ============================================================
-- Estudiantes registrados en el sistema (p. ej. codigo escolar,
-- nombres/apellidos, qr_token y sección a la que pertenecen).
--
-- Modelo oficial (04-BD §6.5): id, codigo (UNIQUE), qr_token (UNIQUE),
-- nombres, apellidos, seccion_id (FK a secciones), activo (default TRUE),
-- created_at, updated_at.
--
-- Restricciones documentadas (04-BD §6.5 y 07-PLAN Prompt 4.1):
--   - codigo   UNIQUE  : código escolar único del estudiante.
--   - qr_token UNIQUE  : único; no debe contener datos personales
--                        (la generación segura llega en Prompt 4.2).
--   - seccion_id NOT NULL + FK fk_estudiantes_seccion.
--
-- Sin ON DELETE CASCADE: los documentos no lo exigen.
-- Sin triggers, sin seeds: solo estructura.
-- ============================================================

CREATE TABLE estudiantes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL UNIQUE,
    qr_token VARCHAR(120) NOT NULL UNIQUE,
    nombres VARCHAR(120) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    seccion_id BIGINT NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_estudiantes_seccion
        FOREIGN KEY (seccion_id)
        REFERENCES secciones(id)
);