-- ============================================================
-- AulaIA — Migración V7: tabla docentes (docs/04-BASE_DE_DATOS §6.2)
-- ============================================================
-- Información académica asociada a un usuario con rol DOCENTE.
--
-- Modelo oficial (04-BD §6.2): id, usuario_id (FK UNIQUE a usuarios),
-- nombres, apellidos, activo (default TRUE), created_at, updated_at.
--
-- Restricciones documentadas (04-BD §6.2 y 07-PLAN Prompt 5.1):
--   - usuario_id NOT NULL UNIQUE : relación 1 a 1 física
--     (usuarios 1 ─── 0..1 docentes); un usuario no puede tener
--     más de un perfil docente.
--   - FK fk_docentes_usuario → usuarios(id).
--
-- Sin ON DELETE CASCADE: los documentos no lo exigen (mantener
-- históricos, 06-FLUJOS #49).
-- Sin triggers, sin seeds: solo estructura.
-- ============================================================

CREATE TABLE docentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL UNIQUE,
    nombres VARCHAR(120) NOT NULL,
    apellidos VARCHAR(120) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_docentes_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuarios(id)
);