-- ============================================================
-- AulaIA — Migración V8: tabla horarios (docs/04-BASE_DE_DATOS §6.7)
-- ============================================================
-- Define cuándo se dicta un curso para una sección determinada
-- (plantilla semanal).
--
-- Modelo oficial (04-BD §6.7): id, curso_id (FK), seccion_id (FK),
-- docente_id (FK), dia_semana SMALLINT, hora_inicio TIME, hora_fin TIME,
-- tolerancia_minutos SMALLINT DEFAULT 10, minutos_antes_apertura SMALLINT
-- DEFAULT 15, activo DEFAULT TRUE, created_at, updated_at.
--
-- Constraints físicas documentadas (04-BD §6.7, nombres oficiales):
--   - ck_horarios_dia_semana : dia_semana BETWEEN 1 AND 7
--   - ck_horarios_tolerancia : tolerancia_minutos >= 0
--   - ck_horarios_apertura   : minutos_antes_apertura >= 0
--   - ck_horarios_horas      : hora_fin > hora_inicio
--
-- Convención oficial para dia_semana (04-BD §6.7):
--   1 = Lunes, 2 = Martes, ..., 7 = Domingo.
--
-- Índices recomendados documentados (04-BD §14): idx_horarios_seccion,
-- idx_horarios_docente, idx_horarios_curso.
--
-- Sin ON DELETE CASCADE: los documentos no lo exigen.
-- Sin triggers, sin seeds: solo estructura.
-- ============================================================

CREATE TABLE horarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curso_id BIGINT NOT NULL,
    seccion_id BIGINT NOT NULL,
    docente_id BIGINT NOT NULL,
    dia_semana SMALLINT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    tolerancia_minutos SMALLINT NOT NULL DEFAULT 10,
    minutos_antes_apertura SMALLINT NOT NULL DEFAULT 15,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_horarios_curso
        FOREIGN KEY (curso_id)
        REFERENCES cursos(id),

    CONSTRAINT fk_horarios_seccion
        FOREIGN KEY (seccion_id)
        REFERENCES secciones(id),

    CONSTRAINT fk_horarios_docente
        FOREIGN KEY (docente_id)
        REFERENCES docentes(id),

    CONSTRAINT ck_horarios_dia_semana
        CHECK (dia_semana BETWEEN 1 AND 7),

    CONSTRAINT ck_horarios_tolerancia
        CHECK (tolerancia_minutos >= 0),

    CONSTRAINT ck_horarios_apertura
        CHECK (minutos_antes_apertura >= 0),

    CONSTRAINT ck_horarios_horas
        CHECK (hora_fin > hora_inicio)
);

CREATE INDEX idx_horarios_seccion
    ON horarios(seccion_id);

CREATE INDEX idx_horarios_docente
    ON horarios(docente_id);

CREATE INDEX idx_horarios_curso
    ON horarios(curso_id);